# Generated by Django 5.2.1 on 2025-08-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('tea', 'Чай'), ('coffee', 'Кофе'), ('accessory', 'Аксессуар')], max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'TeaCategories',
            },
        ),
        migrations.CreateModel(
            name='CoffeeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('capsules', 'Капсулы'), ('ground', 'Молотый'), ('beans', 'В зернах')], max_length=20)),
                ('roast', models.CharField(choices=[('light', 'Слабая'), ('medium', 'Средняя'), ('dark', 'Сильная')], max_length=20)),
                ('q_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('additives', models.ManyToManyField(to='products.additive')),
                ('aromas', models.ManyToManyField(to='products.aroma')),
                ('compositions', models.ManyToManyField(to='products.coffeecomposition')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_attr', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='volume (l)')),
                ('accessory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.accessorytype')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_attr', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TeaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_type', models.CharField(choices=[('bagged', 'Пакетированный'), ('loose', 'На развес')], max_length=20)),
                ('additives', models.ManyToManyField(to='products.additive')),
                ('aromas', models.ManyToManyField(to='products.aroma')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tea_attr', to='products.product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.teacategory')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.PositiveIntegerField(verbose_name='weight (g)')),
                ('pieces', models.PositiveIntegerField()),
                ('text_description_of_count', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'text_description_of_count')},
            },
        ),
    ]
