# Generated by Django 5.2.1 on 2025-08-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['product', 'text_description_of_count']},
        ),
    ]
