# Generated by Django 5.2.1 on 2025-08-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryattribute',
            name='accessory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_attrs', to='products.accessorytype'),
        ),
    ]
