# Generated by Django 5.2.1 on 2025-08-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_accessoryattribute_accessory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeattribute',
            name='additives',
            field=models.ManyToManyField(related_name='coffee_attrs', to='products.additive'),
        ),
        migrations.AlterField(
            model_name='coffeeattribute',
            name='aromas',
            field=models.ManyToManyField(related_name='coffee_attrs', to='products.aroma'),
        ),
        migrations.AlterField(
            model_name='coffeeattribute',
            name='compositions',
            field=models.ManyToManyField(related_name='coffee_attrs', to='products.coffeecomposition'),
        ),
        migrations.AlterField(
            model_name='teaattribute',
            name='additives',
            field=models.ManyToManyField(related_name='tea_attrs', to='products.additive'),
        ),
        migrations.AlterField(
            model_name='teaattribute',
            name='aromas',
            field=models.ManyToManyField(related_name='tea_attrs', to='products.aroma'),
        ),
        migrations.AlterField(
            model_name='teaattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_attrs', to='products.teacategory'),
        ),
    ]
