# Generated by Django 5.2.1 on 2025-08-11 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_coffeeattribute_additives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeecomposition',
            name='percent',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
