# Generated by Django 5.2.1 on 2025-08-12 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coffeecomposition_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeattribute',
            name='compositions',
        ),
        migrations.AddField(
            model_name='coffeeattribute',
            name='arabica_percent',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeeattribute',
            name='liberica_percent',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeeattribute',
            name='robusta_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoffeeComposition',
        ),
    ]
