# Generated by Django 5.2.1 on 2025-08-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_country_manufacturer_alter_product_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
